#!/bin/sh

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
PYTHONPATH=${SCRIPTPATH}/../lib/markdown:$PYTHONPATH
POOLE=${SCRIPTPATH}/../lib/poole/poole.py

if $POOLE --build
then
	cp -a output/* ..
	RETVAL=$?
	echo "git-hook-post-merge completed."
else
	RETVAL=$?
	echo "git-hook-post-merge failed."
fi

return $RETVAL

